// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv_vyXoCkcHQoyNL5SOL-2lKcflqmYNOY',
    appId: '1:34235243467:web:33e830fc07b7e88d9e744e',
    messagingSenderId: '34235243467',
    projectId: 'chatapp-edc6b',
    authDomain: 'chatapp-edc6b.firebaseapp.com',
    storageBucket: 'chatapp-edc6b.appspot.com',
    measurementId: 'G-54ZG76NJJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtJgztJtPfEixH9Fac2h2zu3d4uxdGrc',
    appId: '1:34235243467:android:56268e2b5f4c13699e744e',
    messagingSenderId: '34235243467',
    projectId: 'chatapp-edc6b',
    storageBucket: 'chatapp-edc6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq00kdGy6-Yh1qaWPAfpozL7s51kLyiiY',
    appId: '1:34235243467:ios:fd67097b9b08d6fe9e744e',
    messagingSenderId: '34235243467',
    projectId: 'chatapp-edc6b',
    storageBucket: 'chatapp-edc6b.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq00kdGy6-Yh1qaWPAfpozL7s51kLyiiY',
    appId: '1:34235243467:ios:fd67097b9b08d6fe9e744e',
    messagingSenderId: '34235243467',
    projectId: 'chatapp-edc6b',
    storageBucket: 'chatapp-edc6b.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv_vyXoCkcHQoyNL5SOL-2lKcflqmYNOY',
    appId: '1:34235243467:web:ae936057a6dd3ad59e744e',
    messagingSenderId: '34235243467',
    projectId: 'chatapp-edc6b',
    authDomain: 'chatapp-edc6b.firebaseapp.com',
    storageBucket: 'chatapp-edc6b.appspot.com',
    measurementId: 'G-JLFTRTBSDZ',
  );
}
